In [32]:
import numpy as np

X = np.array([[2.47, 0.65, -1.88], [1.34, 1.17, 2.54], [0.86, -1.73, -1.08]])
Y = np.array([1.24, 2.35, 3.15])

In [50]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [33]:
print("A = ", bmatrix(X))
print("\qauad B = ", bmatrix(Y))

A =  \begin{pmatrix}[ccc]
  2.47 & 0.65 & -1.88\\
  1.34 & 1.17 & 2.54\\
  0.86 & -1.73 & -1.08\\
\end{pmatrix}
\qauad B =  \begin{pmatrix}[ccc]
  1.24 & 2.35 & 3.15\\
\end{pmatrix}


In [34]:
AtA = np.round(X.T @ X, 4)
Atb = np.round(X.T @ Y.T, 4)

print(bmatrix(X.T), bmatrix(X), " = ", bmatrix(AtA))
print(bmatrix(X.T), bmatrix(Y), " = ", bmatrix(Atb))

\begin{pmatrix}[ccc]
  2.47 & 1.34 & 0.86\\
  0.65 & 1.17 & -1.73\\
  -1.88 & 2.54 & -1.08\\
\end{pmatrix} \begin{pmatrix}[ccc]
  2.47 & 0.65 & -1.88\\
  1.34 & 1.17 & 2.54\\
  0.86 & -1.73 & -1.08\\
\end{pmatrix}  =  \begin{pmatrix}[ccc]
  8.6361 & 1.6855 & -2.1688\\
  1.6855 & 4.7843 & 3.6182\\
  -2.1688 & 3.6182 & 11.1524\\
\end{pmatrix}
\begin{pmatrix}[ccc]
  2.47 & 1.34 & 0.86\\
  0.65 & 1.17 & -1.73\\
  -1.88 & 2.54 & -1.08\\
\end{pmatrix} \begin{pmatrix}[ccc]
  1.24 & 2.35 & 3.15\\
\end{pmatrix}  =  \begin{pmatrix}[ccc]
  8.9208 & -1.894 & 0.2358\\
\end{pmatrix}


In [35]:
Atb

array([ 8.9208, -1.894 ,  0.2358])

In [38]:
l = np.eye(3)

In [36]:
AtA

array([[ 8.6361,  1.6855, -2.1688],
       [ 1.6855,  4.7843,  3.6182],
       [-2.1688,  3.6182, 11.1524]])

In [40]:
l[0][0] = round(AtA[0][0]**0.5, 4)
l[1][0] = round(AtA[1][0] / l[0][0], 4)
l[2][0] = round(AtA[2][0] / l[0][0], 4)

l

array([[ 2.9387,  0.    ,  0.    ],
       [ 0.5736,  1.    ,  0.    ],
       [-0.738 ,  0.    ,  1.    ]])

In [41]:
l[1][1] = round((AtA[1][1] - l[1][0]**2)**0.5, 4)
l[2][1] = round((AtA[2][1] - l[1][0] * l[2][0])/l[1][1], 4)

l

array([[ 2.9387,  0.    ,  0.    ],
       [ 0.5736,  2.1108,  0.    ],
       [-0.738 ,  1.9147,  1.    ]])

In [48]:
l[2][2] = round((AtA[2][2] - l[2][0]**2 - l[2][1]**2)**0.5 ,4)
l

array([[ 2.9387,  0.    ,  0.    ],
       [ 0.5736,  2.1108,  0.    ],
       [-0.738 ,  1.9147,  2.6347]])

In [49]:
print(bmatrix(l))

\begin{pmatrix}[ccc]
  2.9387 & 0. & 0.\\
  0.5736 & 2.1108 & 0.\\
  -0.738 & 1.9147 & 2.6347\\
\end{pmatrix}


In [54]:
Atb, l

(array([ 8.9208, -1.894 ,  0.2358]),
 array([[ 2.9387,  0.    ,  0.    ],
        [ 0.5736,  2.1108,  0.    ],
        [-0.738 ,  1.9147,  2.6347]]))

In [53]:
g = [0, 0, 0]
g[0] = round(Atb[0] / l[0][0], 4)
g[1] = round((Atb[1] - l[1][0] * g[0])/l[1][1], 4)
g[2] = round((Atb[2] - l[2][0] * g[0] - l[2][1] * g[1]) / l[2][2], 4)

In [45]:
g = np.array(g)
print(g)

[ 3.0356 -1.7222  2.1914]


In [46]:
x = [0, 0, 0]

x[2] = round(g[2] / l.T[2][2], 4)
x[1] = round((g[1] - l.T[1][2] * x[2]) / l.T[1][1], 4)
x[0] = round((g[0] - l.T[0][2] * x[2] - l.T[0][1] * x[1]) / l.T[0][0], 4)

print(np.array(x))

[ 1.5483 -1.5703  0.8317]


In [56]:
print(f'\\frac{{{g[2]}}}{{{l.T[2][2]}}}={x[2]}, \\newline')
print(f'\\frac{{ {g[1]}-{l.T[1][2]}x_2 }}{{{l.T[1][1]}}}={x[1]}, \\newline')
print(f'\\frac{{ {g[0]} - {l.T[0][2]}x_2 - {l.T[0][1]} x_1 }}{{{l.T[0][0]}}}={x[0]}')

\frac{2.1914}{2.6347}=0.8317, \newline
\frac{ -1.7222-1.9147x_2 }{2.1108}=-1.5703, \newline
\frac{ 3.0356 - -0.738x_2 - 0.5736 x_1 }{2.9387}=1.5483


In [52]:
np.round(X @ np.array(x).T, 2)

array([1.24, 2.35, 3.15])

In [14]:
Y

array([1.24, 2.35, 3.15])

In [64]:
print(bmatrix(np.round(X @ np.array(x).T, 4)))

\begin{pmatrix}
  1.24 & 2.35 & 3.1499\\
\end{pmatrix}


In [93]:
np.linalg.solve(X, Y)

array([ 1.54831936, -1.57034543,  0.83171505])