In [8]:
epsilon = 0.001
def F(x):
    return round(x**3 - 3 * x**2 + 9 * x - 10, 4) # $∃ x_1 \in [0;1] $

def F_derive(x):
    return round(3 * x**2 + 6*x+9, 4)

In [75]:
np.polyval(np.polyder(uran), 2)

9

In [76]:
C = round(1 /10, 4)
print(round(C, 4))

0.1


In [77]:
import numpy as np

uran = np.array([1, -3, 9, -10])

In [78]:
uran = -C * uran
uran[2] = 1 + uran[2]

In [88]:
uran

array([-0.1,  0.3,  0.1,  1. ])

In [87]:
np.polyval(np.polyder(uran), 2)

0.09999999999999998

In [85]:
np.polyder(np.polyder(uran))

array([-0.6,  0.6])

In [55]:
uran[0] *= 3
uran[1] *= 2
uran[2] *= 1
uran[3] *= 0

In [60]:
uran

array([-0.0882,  0.1764,  0.7354,  0.    ])

In [59]:
np.round(np.polyval(uran, 2), 4)

1.4708

In [48]:
uran[0] *= 2
uran[1] *= 1
uran[2] *= 0
uran[3] *= 0

In [51]:
np.polyval(uran, 2)

-0.7056

In [94]:
import numpy as np
import pandas as pd
x = [1]
delta = []
while True:
    x.append(np.round(np.polyval(uran, x[-1]),4))
    delta.append(x[-1]-x[-2])
    if delta[-1] < epsilon:
        a = pd.DataFrame({"x_n-1": x[:-1],
                           "x_n": x[1:],
                          "|x_n-x_n-1|": delta})
        break


a

x_n-1     x_n  |x_n-x_n-1|
0  1.0000  1.3000       0.3000
1  1.3000  1.4173       0.1173
2  1.4173  1.4597       0.0424
3  1.4597  1.4742       0.0145
4  1.4742  1.4790       0.0048
5  1.4790  1.4806       0.0016
6  1.4806  1.4811       0.0005

In [95]:
print(a.to_latex())

\begin{tabular}{lrrr}
\toprule
{} &   x\_n-1 &     x\_n &  |x\_n-x\_n-1| \\
\midrule
0 &  1.0000 &  1.3000 &       0.3000 \\
1 &  1.3000 &  1.4173 &       0.1173 \\
2 &  1.4173 &  1.4597 &       0.0424 \\
3 &  1.4597 &  1.4742 &       0.0145 \\
4 &  1.4742 &  1.4790 &       0.0048 \\
5 &  1.4790 &  1.4806 &       0.0016 \\
6 &  1.4806 &  1.4811 &       0.0005 \\
\bottomrule
\end{tabular}



<ipython-input-95-d10ea41283f4>:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(a.to_latex())
