In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.array([[5.4, -6.2, -0.5], [3.4, 2.3, 0.8], [2.4, -1.1, 3.8]])
b = np.array([0.52, -0.8, 1.8]).T

In [3]:
A[0] = A[0] + A[1]
b[0] = b[0] + b[1]

In [4]:
A[1] = A[1] - A[0]
b[1] -= b[0]

In [197]:
b

array([-0.28, -0.52,  1.8 ])

In [5]:
b[0] = b[0] / A[0][0]
b[1] = b[1] / A[1][1]
b[2] = b[2] / A[2][2]
A[0] = A[0] / A[0][0]
A[1] = A[1] / A[1][1]
A[2] = A[2] / A[2][2]

In [204]:
np.round(b, 4)

array([-0.0318, -0.0839,  0.4737])

In [7]:
B = -1 * np.round(A, 4 )
print(B)

[[-1.      0.4432 -0.0341]
 [ 0.871  -1.     -0.0806]
 [-0.6316  0.2895 -1.    ]]


In [8]:
print(abs(sum(B)+1))

[0.2394 0.7327 0.1147]


In [22]:
c = max(abs(sum(B)+1))

In [21]:
round(1 - c, 4)

TypeError: type numpy.ndarray doesn't define __round__ method

In [11]:
from math import log10

In [24]:
f = lambda B, d: round(log10(0.001 * (1 - B) / d) / log10(B), 2)

In [215]:
round((1 - c) / 0.4737, 4)

0.5643

In [25]:
f(c, round(max(abs(b)),4))

24.05

In [19]:
round(max(abs(b)),4)

(array([0.2394, 0.7327, 0.1147]), 0.4737)

In [42]:
def norm(a):
    return max(abs(a))
epsilon = 0.001
x = [(0, 0, 0)]
delta = [1]
while True:
    if delta[-1] < epsilon:
        result = pd.DataFrame({
            "$x_1^{(k)}": [i[0] for i in x],
            "x_2^{(k)}": [i[1] for i in x],
            "x_3^{(k)}$": [i[2] for i in x],
            "$\Vert x^{(k)}-x^{(k-1)} \Vert $": delta
        })
        break
    else:
        x_1 = round(                     B[0][1]*x[-1][1] + B[0][2] * x[-1][2] + b[0], 4)
        x_2 = round(B[1][0] * x_1                    + B[1][2] * x[-1][2] + b[1], 4)
        x_3 = round(B[2][0] * x_1 + B[2][1] * x_2                   + b[2], 4)
        x.append((x_1, x_2, x_3))
        delta.append(norm(np.array(x[-1])-np.array(x[-2])))



In [27]:
def tabular(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{tabular}[|l|*{'+ str(a.shape[1])+'}{c|}] \hline']
    rv += ['  ' + ' & '.join(l.split()) + r'\\ \hline' for l in lines]
    rv +=  [r'\end{tabular}']
    return '\n'.join(rv)

In [243]:
round((1 - c) / c * epsilon, 5)

0.00036

In [32]:
result

x_1^{(k)}  x_2^{(k)}  x_3^{(k)}  $\Vert x^{(k)}-x^{(k-1)} \Vert $
0     0.0000     0.0000     0.0000                            1.0000
1    -0.0318    -0.1116     0.4615                            0.4615
2    -0.0970    -0.2056     0.4754                            0.0940
3    -0.1392    -0.2434     0.4911                            0.0422
4    -0.1564    -0.2597     0.4973                            0.0172
5    -0.1639    -0.2667     0.5000                            0.0075
6    -0.1671    -0.2697     0.5011                            0.0032
7    -0.1684    -0.2709     0.5016                            0.0013
8    -0.1690    -0.2715     0.5018                            0.0006

In [43]:
print(tabular(result))

\begin{tabular}[|l|*{4}{c|}] \hline
  $x_1^{(k)} & x_2^{(k)} & x_3^{(k)}$ & $\Vert & x^{(k)}-x^{(k-1)} & \Vert & $\\ \hline
  0 & 0.0000 & 0.0000 & 0.0000 & 1.0000\\ \hline
  1 & -0.0318 & -0.1116 & 0.4615 & 0.4615\\ \hline
  2 & -0.0970 & -0.2056 & 0.4754 & 0.0940\\ \hline
  3 & -0.1392 & -0.2434 & 0.4911 & 0.0422\\ \hline
  4 & -0.1564 & -0.2597 & 0.4973 & 0.0172\\ \hline
  5 & -0.1639 & -0.2667 & 0.5000 & 0.0075\\ \hline
  6 & -0.1671 & -0.2697 & 0.5011 & 0.0032\\ \hline
  7 & -0.1684 & -0.2709 & 0.5016 & 0.0013\\ \hline
  8 & -0.1690 & -0.2715 & 0.5018 & 0.0006\\ \hline
\end{tabular}


In [35]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [34]:
check = np.array([[5.4, -6.2, -0.5], [3.4, 2.3, 0.8], [2.4, -1.1, 3.8]])

In [44]:
print(bmatrix(np.round(check @ (np.round(result.iloc[-1][:3], 3) - 0.001).T ,4)))

\begin{pmatrix}
  0.5241 & -0.8051 & 1.7961\\
\end{pmatrix}


In [269]:
np.round(result.iloc[-1][:3], 3).T

x1   -0.169
x2   -0.271
x3    0.502
Name: 14, dtype: float64

In [263]:
np.round(check @ np.round(result.iloc[-1][:3], 3), 4)

array([ 0.5166, -0.7963,  1.8001])

In [ ]:
bmat

In [135]:
test = np.array([[4.5, -1.8, 3.6], [3.1, 2.3, -1.2], [1.8, 2.5, 4.6]])

ans = np.array([0.248, 1.115, -0.225]).T

In [136]:
test @ ans

array([-1.701 ,  3.6033,  2.1989])