In [1]:
import numpy as np
import pandas as pd

In [193]:
A = np.array([[5.4, -6.2, -0.5], [3.4, 2.3, 0.8], [2.4, -1.1, 3.8]])
b = np.array([0.52, -0.8, 1.8]).T

In [194]:
A[0] = A[0] + A[1]
b[0] = b[0] + b[1]

In [195]:
A[1] = A[1] - A[0]
b[1] -= b[0]

In [197]:
b

array([-0.28, -0.52,  1.8 ])

In [198]:
b[0] = b[0] / A[0][0]
b[1] = b[1] / A[1][1]
b[2] = b[2] / A[2][2]
A[0] = A[0] / A[0][0]
A[1] = A[1] / A[1][1]
A[2] = A[2] / A[2][2]

In [199]:
-1 * np.round(A, 4 )

array([[-1.    ,  0.4432, -0.0341],
       [ 0.871 , -1.    , -0.0806],
       [-0.6316,  0.2895, -1.    ]])

In [204]:
np.round(b, 4)

array([-0.0318, -0.0839,  0.4737])

In [182]:
B = -1 * np.round(A, 4 )

In [203]:
print(abs(sum(B)+1))

[0.2394 0.7327 0.1147]


In [201]:
c

0.7327

In [206]:
round(1 - c, 4)

0.2673

In [146]:
B

array([[-1.    ,  0.4432, -0.0341],
       [-0.2941, -1.    ,  0.8824],
       [-0.6316,  0.2895, -1.    ]])

In [73]:
from math import log10
import pandas as pd

In [220]:
f = lambda B, d: round(log10(0.001 * (1 - B) / d) / log10(B), 1)

In [215]:
round((1 - c) / 0.4737, 4)

0.5643

In [223]:
f(c, 0.4737)

24.0

In [244]:
def norm(a):
    return max(abs(a))
epsilon = 0.001
x = [(0, 0, 0)]
delta = [1]
while True:
    if delta[-1] < round((1 - c) / c * epsilon, 5):
        result = pd.DataFrame({
            "x1": [i[0] for i in x],
            "x2": [i[1] for i in x],
            "x3": [i[2] for i in x],
            "xk-xk-1": delta
        })
        break
    else:
        x_1 = round(                     B[0][1]*x[-1][1] + B[0][2] * x[-1][2] + b[0], 4)
        x_2 = round(B[1][0] * x[-1][0]                    + B[1][2] * x[-1][2] + b[1], 4)
        x_3 = round(B[2][0] * x[-1][0] + B[2][1] * x[-1][1]                    + b[2], 4)
        x.append((x_1, x_2, x_3))
        delta.append(norm(np.array(x[-1])-np.array(x[-2])))



In [240]:
def tabular(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{tabular}[|l|*{'+ str(a.shape[1])+'}{c|}] \hline']
    rv += ['  ' + ' & '.join(l.split()) + r'\\ \hline' for l in lines]
    rv +=  [r'\end{tabular}']
    return '\n'.join(rv)

In [243]:
round((1 - c) / c * epsilon, 5)

0.00036

In [245]:
print(tabular(result))

\begin{tabular}[|l|*{4}{c|}] \hline
  x1 & x2 & x3 & xk-xk-1\\ \hline
  0 & 0.0000 & 0.0000 & 0.0000 & 1.0000\\ \hline
  1 & -0.0318 & -0.0839 & 0.4737 & 0.4737\\ \hline
  2 & -0.0852 & -0.1497 & 0.4695 & 0.0658\\ \hline
  3 & -0.1142 & -0.1959 & 0.4842 & 0.0462\\ \hline
  4 & -0.1352 & -0.2224 & 0.4891 & 0.0265\\ \hline
  5 & -0.1471 & -0.2411 & 0.4947 & 0.0187\\ \hline
  6 & -0.1555 & -0.2519 & 0.4968 & 0.0108\\ \hline
  7 & -0.1604 & -0.2594 & 0.4990 & 0.0075\\ \hline
  8 & -0.1638 & -0.2638 & 0.4999 & 0.0044\\ \hline
  9 & -0.1658 & -0.2668 & 0.5008 & 0.0030\\ \hline
  10 & -0.1671 & -0.2686 & 0.5012 & 0.0018\\ \hline
  11 & -0.1680 & -0.2698 & 0.5015 & 0.0012\\ \hline
  12 & -0.1685 & -0.2706 & 0.5017 & 0.0008\\ \hline
  13 & -0.1689 & -0.2711 & 0.5018 & 0.0005\\ \hline
  14 & -0.1691 & -0.2714 & 0.5019 & 0.0003\\ \hline
\end{tabular}


In [264]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [121]:
check = np.array([[5.4, -6.2, -0.5], [3.4, 2.3, 0.8], [2.4, -1.1, 3.8]])

In [276]:
print(bmatrix(np.round(check @ (np.round(result.iloc[-1][:3], 3) - 0.001) ,5)))

\begin{pmatrix}
  0.5179 & -0.8028 & 1.795\\
\end{pmatrix}


In [269]:
np.round(result.iloc[-1][:3], 3).T

x1   -0.169
x2   -0.271
x3    0.502
Name: 14, dtype: float64

In [263]:
np.round(check @ np.round(result.iloc[-1][:3], 3), 4)

array([ 0.5166, -0.7963,  1.8001])

In [ ]:
bmat

In [135]:
test = np.array([[4.5, -1.8, 3.6], [3.1, 2.3, -1.2], [1.8, 2.5, 4.6]])

ans = np.array([0.248, 1.115, -0.225]).T

In [136]:
test @ ans

array([-1.701 ,  3.6033,  2.1989])