In [108]:
import numpy as np

A = np.array([
    [3.75, -0.28, 0.17],
    [2.11, -0.11, -0.12],
    [0.22, -3.17, 1.81]
])

In [50]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}[ccc|ccc]']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)


In [24]:
print(bmatrix(A))

\begin{bmatrix}
  3.75 & -0.28 & 0.17\\
  2.11 & -0.11 & -0.12\\
  0.22 & -3.17 & 1.81\\
\end{bmatrix}


In [109]:
def calc(A, B, j, i, elem):
    A[i] = A[j]*elem/A[j][j] + A[i]
    B[i] = B[j]*elem/A[j][j] + B[i]

eye = np.eye(3)

i = 0
b = 1
c = 2
eye[b] = np.round(eye[i] * -A[b][i] / A[i][i] + eye[b], 4)
eye[c] = np.round(eye[i] * -A[c][i] / A[i][i] + eye[c], 4)

A[b] = np.round(A[i] * -A[b][i] / A[i][i] + A[1], 4)
A[c] = np.round(A[i] * -A[c][i] / A[i][i] + A[2], 4)

In [111]:
A

array([[ 3.75  , -0.28  ,  0.17  ],
       [ 0.    ,  0.0475, -0.2157],
       [ 0.    , -3.1536,  1.8   ]])

In [112]:
eye

array([[ 1.    ,  0.    ,  0.    ],
       [-0.5627,  1.    ,  0.    ],
       [-0.0587,  0.    ,  1.    ]])

In [113]:
i = 1
b = 0
c = 2
eye[b] = np.round(eye[i] * -A[b][i] / A[i][i] + eye[b], 4)
eye[c] = np.round(eye[i] * -A[c][i] / A[i][i] + eye[c], 4)

A[b] = np.round(A[i] * -A[b][i] / A[i][i] + A[b], 4)
A[c] = np.round(A[i] * -A[c][i] / A[i][i] + A[c], 4)

In [114]:
A

array([[  3.75  ,   0.    ,  -1.1015],
       [  0.    ,   0.0475,  -0.2157],
       [  0.    ,   0.    , -12.5207]])

In [115]:
eye

array([[ -2.317 ,   5.8947,   0.    ],
       [ -0.5627,   1.    ,   0.    ],
       [-37.4172,  66.3916,   1.    ]])

In [95]:
C = np.array([
    [3.75, -0.28, 0.17],
    [2.11, -0.11, -0.12],
    [0.22, -3.17, 1.81]
])

In [125]:
np.round(np.linalg.det(C), 7)

-2.22935

In [126]:
np.round(3.75 * 0.0475 * -12.5208, 7)

-2.2302675

In [116]:
i = 2
b = 0
c = 1
eye[b] = np.round(eye[i] * -A[b][i] / A[i][i] + eye[b], 4)
eye[c] = np.round(eye[i] * -A[c][i] / A[i][i] + eye[c], 4)

A[b] = np.round(A[i] * -A[b][i] / A[i][i] + A[b], 4)
A[c] = np.round(A[i] * -A[c][i] / A[i][i] + A[c], 4)

In [117]:
eye

array([[ 9.74800e-01,  5.39000e-02, -8.80000e-02],
       [ 8.19000e-02, -1.43800e-01, -1.72000e-02],
       [-3.74172e+01,  6.63916e+01,  1.00000e+00]])

In [118]:
A

array([[  3.75  ,   0.    ,   0.    ],
       [  0.    ,   0.0475,   0.    ],
       [  0.    ,   0.    , -12.5207]])

In [120]:
eye[0] = eye[0]/A[0][0]
eye[1] = eye[1]/A[1][1]
eye[2] = eye[2]/A[2][2]

In [129]:
eye = np.round(eye, 4)

In [130]:
print(bmatrix(eye))

\begin{pmatrix}[ccc|ccc]
  0.2599 & 0.0144 & -0.0235\\
  1.7242 & -3.0274 & -0.3621\\
  2.9884 & -5.3025 & -0.0799\\
\end{pmatrix}


In [98]:
eye[0]/A[0][0]

array([ 2.02624   , -3.12946667,  0.02346667])

In [90]:
np.linalg.inv(C)

array([[ 0.25994124,  0.01439882, -0.02345975],
       [ 1.72494225, -3.02783322, -0.36275147],
       [ 2.98943638, -5.30464037, -0.07997847]])

In [139]:
np.round(C @ eye)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [141]:
print(bmatrix(C), bmatrix(eye))

\begin{pmatrix}[ccc|ccc]
  3.75 & -0.28 & 0.17\\
  2.11 & -0.11 & -0.12\\
  0.22 & -3.17 & 1.81\\
\end{pmatrix} \begin{pmatrix}[ccc|ccc]
  0.2599 & 0.0144 & -0.0235\\
  1.7242 & -3.0274 & -0.3621\\
  2.9884 & -5.3025 & -0.0799\\
\end{pmatrix}


In [142]:
print(bmatrix(np.eye(3)))

\begin{pmatrix}[ccc|ccc]
  1. & 0. & 0.\\
  0. & 1. & 0.\\
  0. & 0. & 1.\\
\end{pmatrix}
