In [67]:
import numpy as np

X = np.array([[2.47, 0.65, -1.88], [1.34, 1.17, 2.54], [0.86, -1.73, -1.08]])

Y = np.array([1.24, 2.35, 3.15]).T

In [10]:
X

array([[ 2.47,  0.65, -1.88],
       [ 1.34,  1.17,  2.54],
       [ 0.86, -1.73, -1.08]])

In [68]:
X[1] = np.round(X[0] * (1.34/X[0][0]) - X[1], 3)
X[2] = np.round(X[0] * (0.86/X[0][0]) - X[2], 3)
Y[1] = np.round(Y[0] * 1.34/X[0][0] - Y[1], 3)
Y[2] = np.round(Y[0] * 0.86/X[0][0] - Y[2], 3)

In [29]:
X, Y

(array([[ 2.47 ,  0.65 , -1.88 ],
        [ 0.   , -0.817, -3.56 ],
        [ 0.   ,  1.956,  0.425]]),
 array([ 1.24 , -1.677, -2.718]))

In [69]:
X[2] = np.round(X[1] * (X[2][1] / X[1][1]) - X[2], 3)

In [70]:
Y[2] = np.round(Y[1] * (1.956 / (-0.818)) - Y[2], 3)

In [32]:
X

array([[ 2.47 ,  0.65 , -1.88 ],
       [ 0.   , -0.817, -3.56 ],
       [-0.   ,  0.   ,  8.098]])

In [46]:
X

array([[ 2.47 ,  0.65 , -1.88 ],
       [ 0.   , -0.817, -3.56 ],
       [-0.   ,  0.   ,  8.098]])

In [71]:
x = [0, 0, 0]
x[2] = round(Y[2] / X[2][2], 3)

In [72]:
x[1] = round((Y[1] + X[1][1] * x[2]) / X[1][1], 3)

In [73]:
x[0] = round((Y[0] - X[0][2] * x[2] - X[0][1] * x[1]) / X[0][0], 3)

In [74]:
x

[0.376, 2.884, 0.831]

In [66]:
X @ np.array(x).T

array([ 1.24104 , -5.314588,  6.729438])

In [23]:
x_1 = round(0.502 - 0.263 * (-1.571) + 0.761 * 0.832, 3)

In [24]:
res = [x_1, x_2, x_3]

NameError: name 'x_2' is not defined

In [63]:
res

[1.548, -1.571, 0.832]

In [21]:
for i in range(3):
    _sum = 0
    for j in range(3):
        print(f'{X[i][j]} * {res[j]}', end=" + ")
        # _sum += X[i][j] * res[j]
    print(f'= {Y[i]};\\\\')
    # _sum = round(_sum, 3)
    # if _sum == Y[i]:
    #     print(_sum)
    #     print(True)
    # else:
    #     print(_sum, Y[i])
    #     print(False)
    # print(f' = {Y[i]}\\\\')

NameError: name 'res' is not defined